### ISSUE TITLE
Unable to retrieve very lage columnID's

### ISSUE THREAD

**Issue by maartenheremans** [pilosa/pilosa#1147] opened 2018-02-25 10:37 UTC
When inserting a bit at columnid: 9,223,372,036,854,775,806 .   (INT64 max - 1)
And then try to retrieve the row, we get a panic in pilosa:

PANIC: runtime error: makeslice: len out of range
goroutine 82 [running]:
runtime/debug.Stack(0xc420060000, 0x1f4, 0xbfec40)
	/usr/local/go/src/runtime/debug/stack.go:24 +0xa7
github.com/pilosa/pilosa.(*Handler).ServeHTTP.func1(0xc067e0, 0xc420060000, 0xc420137340)
	/go/src/github.com/pilosa/pilosa/handler.go:158 +0x91
panic(0xab38a0, 0xbfec40)
	/usr/local/go/src/runtime/panic.go:505 +0x229
github.com/pilosa/pilosa.(*Executor).Execute(0xc4201f0820, 0xc07320, 0xc42056c180, 0xc4201b400c, 0x4, 0xc42043d300, 0x0, 0x0, 0x0, 0xc420024568, ...)
	/go/src/github.com/pilosa/pilosa/executor.go:100 +0x156
github.com/pilosa/pilosa.(*Handler).handlePostQuery(0xc420137340, 0xc067e0, 0xc420060000, 0xc4201c4300)
	/go/src/github.com/pilosa/pilosa/handler.go:267 +0x2f4
github.com/pilosa/pilosa.(*Handler).(github.com/pilosa/pilosa.handlePostQuery)-fm(0xc067e0, 0xc420060000, 0xc4201c4300)
	/go/src/github.com/pilosa/pilosa/handler.go:131 +0x48
net/http.HandlerFunc.ServeHTTP(0xc420234eb0, 0xc067e0, 0xc420060000, 0xc4201c4300)
	/usr/local/go/src/net/http/server.go:1947 +0x44
github.com/pilosa/pilosa/vendor/github.com/gorilla/mux.(*Router).ServeHTTP(0xc42001c420, 0xc067e0, 0xc420060000, 0xc4201c4300)
	/go/src/github.com/pilosa/pilosa/vendor/github.com/gorilla/mux/mux.go:150 +0xed
github.com/pilosa/pilosa.(*Handler).ServeHTTP(0xc420137340, 0xc067e0, 0xc420060000, 0xc4201c4000)
	/go/src/github.com/pilosa/pilosa/handler.go:166 +0xdd
net/http.serverHandler.ServeHTTP(0xc420158000, 0xc067e0, 0xc420060000, 0xc4201c4000)
	/usr/local/go/src/net/http/server.go:2694 +0xbc
net/http.(*conn).serve(0xc420160320, 0xc07260, 0xc420140200)
	/usr/local/go/src/net/http/server.go:1830 +0x651
created by net/http.(*Server).Serve
	/usr/local/go/src/net/http/server.go:2795 +0x27b

This can be reproduced easily via the webui:

:create index test
:use index test
:create frame test2
SetBit(frame=test2, rowID=0, columnID=9223372036854775806)
Bitmap(frame=test2, rowID=0)

**Comment by jaffee** [comment] 2018-02-26 14:37
@maartenheremans Thanks for the very clear bug report - this is actually a duplicate of #591 and some follow-on work is discussed in #593. 

The short story is that for both row and column ids in Pilosa, you should strive to use sequential ids. There is some work in progress to remove this restriction, and to allow one to use arbitrary strings for row and column ids, but it is still early.

I'll try to find a good place to make this restriction more clear in our documentation - let us know if there is anything else we can help with!

**Closed** 2018-03-20 15:37 UTC
Labels: duplicate
