### ISSUE TITLE
another panic in RLE branch while importing taxi data (Bitmap.UnmarshalBinary)

### ISSUE THREAD

**Issue by jaffee** [pilosa/pilosa#718] opened 2017-07-10 18:26 UTC
This import was using pdk version `a54a1d7` from my fork (github.com/jaffee/pdk)
```
Pilosa v0.4.0-120-g2b27f36, build time 2017-07-10T15:59:08+0000
Using data from: /home/ubuntu/pilosa/data1
Listening as http://node0.testrle1.sandbox.pilosa.com:10101
2017/07/10 18:02:23 http: panic serving 10.0.1.33:51104: runtime error: slice bounds out of range
goroutine 3931 [running]:
net/http.(*conn).serve.func1(0xc42013c140)
	/usr/local/go/src/net/http/server.go:1721 +0xd0
panic(0xab6860, 0xeba2d0)
	/usr/local/go/src/runtime/panic.go:489 +0x2cf
github.com/pilosa/pilosa/roaring.(*Bitmap).UnmarshalBinary(0xc444f4af00, 0x7f73a1d47000, 0x5f7090, 0x5f7090, 0x0, 0x0)
	/home/ubuntu/go/src/github.com/pilosa/pilosa/roaring/roaring.go:711 +0x952
github.com/pilosa/pilosa.(*Fragment).openStorage(0xc42c4c4000, 0x51, 0xc43591e140)
	/home/ubuntu/go/src/github.com/pilosa/pilosa/fragment.go:232 +0x4c5
github.com/pilosa/pilosa.(*Fragment).snapshot(0xc42c4c4000, 0x0, 0x0)
	/home/ubuntu/go/src/github.com/pilosa/pilosa/fragment.go:1066 +0x8df
github.com/pilosa/pilosa.(*Fragment).Import(0xc42c4c4000, 0xc4846e6000, 0xb6cc0, 0xde000, 0xc462814000, 0xb6cc0, 0xde000, 0x0, 0x0)
	/home/ubuntu/go/src/github.com/pilosa/pilosa/fragment.go:999 +0x154
github.com/pilosa/pilosa.(*Frame).Import(0xc4202c6580, 0xc484eba000, 0xb6cc0, 0xde000, 0xc45aaba000, 0xb6cc0, 0xde000, 0xc472e96000, 0xb6cc0, 0xb6cc0, ...)
	/home/ubuntu/go/src/github.com/pilosa/pilosa/frame.go:598 +0x8f7
github.com/pilosa/pilosa.(*Handler).handlePostImport(0xc42021f8f0, 0xe86e80, 0xc422a242a0, 0xc4235ba600)
	/home/ubuntu/go/src/github.com/pilosa/pilosa/handler.go:1028 +0x638
github.com/pilosa/pilosa.(*Handler).(github.com/pilosa/pilosa.handlePostImport)-fm(0xe86e80, 0xc422a242a0, 0xc4235ba600)
	/home/ubuntu/go/src/github.com/pilosa/pilosa/handler.go:119 +0x48
net/http.HandlerFunc.ServeHTTP(0xc420255dc0, 0xe86e80, 0xc422a242a0, 0xc4235ba600)
	/usr/local/go/src/net/http/server.go:1942 +0x44
github.com/pilosa/pilosa/vendor/github.com/gorilla/mux.(*Router).ServeHTTP(0xc420214640, 0xe86e80, 0xc422a242a0, 0xc4235ba600)
	/home/ubuntu/go/src/github.com/pilosa/pilosa/vendor/github.com/gorilla/mux/mux.go:114 +0x10c
github.com/pilosa/pilosa.(*Handler).ServeHTTP(0xc42021f8f0, 0xe86e80, 0xc422a242a0, 0xc4235ba400)
	/home/ubuntu/go/src/github.com/pilosa/pilosa/handler.go:142 +0x91
net/http.serverHandler.ServeHTTP(0xc4202d2000, 0xe86e80, 0xc422a242a0, 0xc4235ba400)
	/usr/local/go/src/net/http/server.go:2568 +0x92
net/http.(*conn).serve(0xc42013c140, 0xe87b80, 0xc4275160c0)
	/usr/local/go/src/net/http/server.go:1825 +0x612
created by net/http.(*Server).Serve
	/usr/local/go/src/net/http/server.go:2668 +0x2ce
```

### Expected behavior
Not panic.

### Actual behavior
panic.

### Steps to reproduce the behavior
Ran `pdk taxi -f /home/ubuntu/go/src/github.com/pilosa/pdk/usecase/taxi/greenAndYellowUrls.txt --pilosa node1.testrle1.sandbox.pilosa.com:10101 -b 1000000 -c 4` using pdk version `a54a1d7` from my fork (github.com/jaffee/pdk).

Pilosa version `2b27f36`. 

This will not necessarily reproduce every time, although this is the second panic produced this way.

### Information about your environment (OS/architecture, CPU, RAM, cluster/solo, configuration, etc.)

3-node r4.xlarge cluster on AWS. Importing from c4.2xlarge. This was all deployed from the infrastructure repo (so using that AMI).

**Comment by alanbernstein** [comment] 2017-07-11 20:41
I did some debugging with a sample fragment file from jaffee, and it looks like the problem is earlier than this. The obvious next place is Bitmap.WriteTo, but the sample file can't help with that, so I'm trying to reproduce at a higher level. @tgruben and I were trying to figure out if something else in the import pipeline could be the problem, no guesses so far.

**Comment by alanbernstein** [comment] 2017-07-25 18:21
This was caused by a mismatch between the logic that sets the container type in `Bitmap.UnmarshalBinary` (type is not stored explicitly but rather inferred from cardinality), and the logic that switches container types to minimize storage size in `container.Optimize` - this function name is appropriate, but it obscures the fact that it is the counterpart of the type decision code in `UnmarshalBinary`. 

I'm cleaning up a fix for this now, and we are also looking into storing the type explicitly to prevent a repeat of this.

#713 may be related.

**Closed** 2017-08-08 17:17 UTC
Labels: bug
