### ISSUE TITLE
.keys file doesn't get cleared even when index is deleted

### ISSUE THREAD

**Issue by shaqque** [pilosa/pilosa#1976] opened 2019-05-21 04:12 UTC
For bugs, please provide the following:

### What's going wrong?
The .keys file (generated by translate.go) doesn't get deleted even when all indexes are deleted. Also, adding new indexes after deletion with string keys increases the .keys size and can theoretically reach infinity.

In my testing, the .keys file remained at 153 MB even after all indexes are deleted. After adding new indexes, the .keys file reached 243 MB.

### What was expected?
.keys file to be empty or at least reduced if some index with string keys is deleted.

### Steps to reproduce the behavior
1. Add any index and field with string keys
2. Check .keys size
3. Delete index
4. Check .keys size again (it will be the same)
5. Add new index and field with string keys
6. Check .keys size (should now be larger)

### Information about your environment (OS/architecture, CPU, RAM, cluster/solo, configuration, etc.)
MacOS 10.14.4 (Mojave), Pilosa 1.3.0

### Success criteria (What criteria will consider this ticket closeable?)
.keys file is deleted when all indexes are deleted, or at least .keys file size is reduced when some index with string keys is deleted.

**Comment by jaffee** [comment] 2019-05-21 17:34
see `Holder.DeleteIndex` (holder.go) — there is no code to remove an index from the TranslateFile, so this would need to be implemented. I'm not sure what the difficulty level looks like.

**Comment by benbjohnson** [comment] 2019-06-06 15:07
@jaffee The issue is that the translation file [exists on the `Holder`](https://github.com/benbjohnson/pilosa/blob/7ff684c193dd6c0fa71b8ea9b0d0141e17adc3dd/holder.go#L57) so if an index is deleted then other indexes may rely on the same data.

The best approach is probably to have each index maintain its own translation file. That would allow us to remove the `index` argument in functions like `TranslateColumnsToUint64()`.

**Comment by jaffee** [comment] 2019-07-30 14:52
moving to in progress due to #2042

**Comment by travisturner** [comment] 2019-11-04 17:58
addressed by #2042

**Closed by travisturner** 2019-11-04 17:58 UTC
Labels: keytranslation
