### ISSUE TITLE
Implement gossip seed auto-discovery

### ISSUE THREAD

**Issue by yuce** [pilosa/pilosa#900] opened 2017-10-24 12:32 UTC
### Description

Currently the gossip seed for a node should be specified manually with `gossip.seed` parameter. `gossip.seed` accepts only a single host. This is hard to use in production. For example assume that the nodes run under a supervisor process (which should always be the case on production). A node may be restarted  anytime (maybe due to failure) which requires `gossip.seed` to be  set to an available host in the cluster. In that case, the administrator of the cluster should check the health of the hosts in the cluster and decide on a host to supply as the `gossip.seed` of the restarted node. Until restarted with the correct `gossip.seed`, a node cannot communicate with other hosts in the cluster.

In order to make a Pilosa cluster more resilient and correctly start/restart without intervention a node should be able to discover the seed node automatically. There could be two ways to approach this problem, observing that each host in the cluster is a potential gossip seed with a port different from the HTTP(s) port:
1) We can deprecate `gossip.seed` and `gossip.port` and determine the gossip port of a node automatically; e.g., `gossip_port = http_port + 1000`. A node would iterate on the addresses of all cluster nodes, inferring the gossip address until a healthy node is found.
2) We can extend `gossip.seed` to accept a list of addresses/ports instead of a single one and during startup a node would iterate on gossip seeds until a healthy node is found.

### Success criteria (What criteria will consider this ticket closeable?)

During startup a node can discover a healthy gossip node without intervention.

**Comment by travisturner** [comment] 2017-10-24 13:49
memberlist already supports a list of seeds, we just need to implement that in the pilosa config. see the existing `TODO` in `gossip/gossip.go`:
```
nodes := []*pilosa.Node{&pilosa.Node{Scheme: "gossip", Host: g.config.gossipSeed}} //TODO: support a list of seeds
```

I'm not sure I understand how cluster discovery would work without specifying a seed (remember that the host list in the config is going away and we will rely solely on gossip to determine cluster membership). I think if we just address that `TODO` so that more than one seed can be specified that should be good. Does that make sense to you @yuce?

**Comment by yuce** [comment] 2017-10-24 14:45
@travisturner we can use `cluster.hosts` to find out `gossip.seed` after we enable multiple hosts for the gossip seed. E.g., `pilosa server --cluster.hosts node1.pilosa.com:10101,node2.pilosa.com:10102` would set `--gossip.seed node1.pilosa.com:11101,node2.pilosa.com:11102` (by adding 1000 to the host port). But I think just enabling multiple hosts in `gossip.seed` would be great for now.

**Comment by jaffee** [comment] 2017-10-24 14:46
I agree this is an area where we could improve resiliency, but I don't think it's a high priority at the moment.

If we decide that having a static list of seeds in the configuration is not enough, each node in the cluster could persist a list of its last known set of gossip peers to disk. That way if the node fails, it could retry any node which it was configured with, and/or any node that it had found previously through memberlist. I can imagine some weird bugs that could happen doing something like this though, so I think it would be best to defer until people are running clusters big enough for this to be a problem.

**Comment by yuce** [comment] 2017-10-24 14:50
The main problem to solve is, we should have the ability to start/restart a node with the same parameters and everything should work OK since that's what a supervisor would do if a node fails. E.g., if we specify the seed `foo.com:12000` for a node in its config and `foo.com:12000` is down, that node won't be able to restart currently. I think we need to prioritize this, since this directly affects the production (especially since we already have a tivial solution).

**Comment by travisturner** [comment] 2017-10-24 15:10
`cluster.hosts` is being deprecated with the cluster-resize functionality.
I think all we need to do is modify our config to accept a list of gossip seeds.

**Comment by travisturner** [comment] 2018-02-08 17:56
In the `cluster-resize` branch, each node writes a `.topology` file to disk which is available on restart. Unfortunately, since we changed from using `NodeID` instead of `URI` to identify nodes, that `.topology` does not include the `URIs` of the other nodes in the cluster.

We could modify the `.topology` logic to store `URI` as well as `NodeID` to be used *only* in the case of a restart for the purpose of seeding gossip. (In a restart situation, the restarting node would seed gossip with any seed specified by the config as well as the list of nodes in the `.topology` file.)

**Comment by codysoyland** [comment] 2018-02-14 14:55
I think it makes sense to do both of the following:
1. Allow a list of seeds (instead of a single) in the config file.
2. Store the discovered seeds in `.topology` alongside the NodeIDs. Use them only in case that the seeds in the config file are unavailable.

I am working on a patch.

**Comment by codysoyland** [comment] 2018-02-27 16:01
I merged #1133 which solves (1.) above. After thinking through different operational scenerios, I now think that storing discovered seeds in `.topology` could result in unintended behavior, like unintentionally adding removed nodes back to a cluster. Additionally, it would more complexity to the code. As long as we store multiple seeds in the config file, that should be good enough. I will close this for now -- if anybody objects, feel free to reopen and we can explore this in the future.

**Closed by codysoyland** 2018-02-27 16:01 UTC
Labels: cluster, enhancement

**Comment by jaffee** [comment] 2018-02-27 19:04
I think I object. Node removal operations should be totally synchronous - that is, every node in the cluster should acknowledge receipt and handling of a node removal before it is considered complete. This handling should include removing that node from any internal persistent state. 

Our goal should be to make Pilosa's configuration as lightweight as possible, and needing to specify multiple gossip seeds and remembering to remove them from config files if nodes are removed or add more if nodes are added doesn't seem like a fun scenario from an operational perspective.

@codysoyland I would actually reverse your 2. from above and say:

> Store the discovered seeds in .topology alongside the NodeIDs. Use the config file only if the topology file doesn't exist.

Once a node has joined a cluster, manually editing cluster state is dangerous - any changes to the cluster need to be agreed upon within the cluster.

I haven't fully worked this out, so there may be some missing scenarios, but I think in general our config handling needs to move to be more "cluster aware" and less "file per node". So that you're viewing and updating config through an API which can do the right thing across the cluster rather than editing files on nodes and restarting processes.

**Comment by codysoyland** [comment] 2018-02-28 15:40
My thinking on the matter is this. Yes, I agree that config should largely be cluster-wide and modifying config values should not be something we require often. I just don't see the gossip seed as a setting that will have to be modified often. Every node can have the same 2 or 3 seeds and you will likely never have to touch them. So in this case, I don't think we're putting much pain on our users.

Secondly, if a user _does_ chose to modify the config and change the seeds, I think it would be counter-intuitive, dangerous even, to have it automatically try the seeds in the (opaque-to-the-user) topology file. Especially in production scenerios where accidentally triggering a cluster resize would result in unintended unavailability. While we like to see the seed auto-discovery as a useful and simplifying feature, I think it can cause surprises, which are not welcome for ops people. This is a case where I believe the user should be forced to be explicit.

**Comment by jaffee** [comment] 2018-02-28 16:14
I definitely see your point and will defer to your ops wisdom 🙏
