### ISSUE TITLE
Fragment endpoint should always return scheme

### ISSUE THREAD

**Issue by j0shua** [pilosa/pilosa#928] opened 2017-11-03 18:33 UTC
### Expected behavior
The `/fragment/nodes` endpoint should always return a `scheme` property in the response json. [Alternatively Node structs in the import library should have a default scheme.]

### Actual behavior
When running via the docker container on localhost a request to get fragments returns `[{"host":"localhost:10101"}]` with no `scheme` field. 

This results in failure to import data for anything that calls [Import](https://github.com/pilosa/pilosa/blob/master/client.go#L287) (for example using pdk/ctl fails). 

This is due to the fact that Import calls [FragmentNodes](https://github.com/pilosa/pilosa/blob/master/client.go#L300) which makes a request to get the location of fragments and the [client library](https://github.com/pilosa/pilosa/blob/master/client.go#L228) decodes the response into a [Node ](https://github.com/pilosa/pilosa/blob/master/cluster.go#L41) struct that has no default for the scheme. When the Node is then used (back in the Import method) the subsequent call to [ImportNode](https://github.com/pilosa/pilosa/blob/master/client.go#L307) fails since there is no scheme.

 
### Steps to reproduce the behavior
Run an instance of pilosa in docker as per the "get started" documentation. Create an index and frame.
Make a request for fragments:
`curl "http://localhost:10101/fragment/nodes?index=segment&slice=0"` 

Response is:
`[{"host":"localhost:10101"}]` 
Note the lack of a protocol field in the response payload.

### Information about your environment (OS/architecture, CPU, RAM, cluster/solo, configuration, etc.)
Mac running pilosa locally in docker.

### Success criteria (What criteria will consider this ticket closeable?)
All requests to the fragments endpoint consistently return a payload including protocol.

**Comment by travisturner** [comment] 2017-11-06 14:32
Hey @j0shua thanks for pointing this out.

We have actually been working to change from using `host`/`port` to using a `URI` struct which is defined in `uri.go`. That work is happening on the [cluster-resize](https://github.com/pilosa/pilosa/pull/904) branch, and we're actively working to get that released soon.

Those changes would mean that instead of a `Node` being defined as:
```
type Node struct {
    Scheme string `json:"scheme"`
    Host   string `json:"host"`
}
```
it will look like this:
```
type Node struct {
    URI URI `json:"uri"`
}
```
with the `URI` struct defined as:
```
type URI struct {
    scheme string `json:"scheme"`
    host   string `json:"host"`
    port   uint16 `json:"port"`
}
```
so the response to the `/fragment/nodes` endpoint will be:
[{"uri":{"scheme":"http","host":"localhost","port":10101}}]

**Comment by jaffee** [comment] 2017-11-07 04:59
Hi @j0shua - thanks for the bug report, and glad to hear you found the pdk code fairly clear - we strive for simplicity!

Right now, it looks like master branch of the PDK is not compatible with v0.7.1 of Pilosa (which is what you get in the docker image). I think we're going to need to start tagging releases of our libraries and tools (like the PDK) along with Pilosa so that users can find compatible versions.

For now though, the PDK and Pilosa master do seem to play nicely together, so if you don't mind, building Pilosa from source is pretty straightforward (`make install`), and running it with the default config is just `pilosa server`. We should be cutting a 0.8.0 in the next week or two with only minor changes.

As far as the PDK goes, I actually recommend using the LevelDB translator rather than BoltDB - it supports faster writes, and has been used quite a bit more because of that.

As to your last question, I'm thrilled that you're using the PDK, and would certainly recommend you continue down that path, though I must warn you that fairly significant changes are coming, so expect a bit of refactoring (which I'm happy to help with). 

Please keep the issues coming as you encounter problems, and feel free to hit us up here or on gophers.slack.com in the #pilosa channel!

**Comment by j0shua** [comment] 2017-12-04 16:37
Hi Pilosa Team,

Similar to the issue above, if you start the server by binding to 0.0.0.0 (e.g. `pilosa server -b 0.0.0.0:10101`) then you can't load data to it from another machine by using `pilosa import --host XX.XX.XX.XX` since when it queries the pilosa server for its address it will self-identify as `0.0.0.0` instead of an IP or DNS name.

Getting back to my primary concern: efficiently loading data into Pilosa ...

I'm currently running a 3 node cluster of r4.8xlarge instances following the setup described in the docs for [setting up a cluster](https://www.pilosa.com/docs/latest/configuration/#example-cluster-configuration) and attempting to load a large amount of segmentation data. (About 200 files with 40 Million lines per file for ~8Billion segment/userID relationship pairs.)

I pre-sorted the part files of rowID/columnID pairs like so:
```
1004,13
1004,15
1004,110
1004,124
1004,138
1004,141
1004,192
1004,209
1004,227
1004,230
...
```

I'm then loading this data to the cluster from another (separate) ec2 instance in the VPC via `pilosa import --host 10.0.0.80 -i INDEX_NAME -f FRAME_NAME FILENAME.csv`. The write throughput seems to only be 1100-1700 bits set per second which is prohibitive for adopting Pilosa into our use case. At this rate even the initial load is will take an exceeding long time. I believe the data is pretty close to the exact use-case Pilosa was designed for, so I'm wondering if I am doing something wrong.

What is the expected throughput? 
What is the recommended way to be able to get the highest write per/second rate?
Does it matter which value / attribute is used for the rowID vs columnID? Is that true even if reverseEnabled = true ?

Thanks for the help.

**Comment by jaffee** [comment] 2017-12-05 18:16
Hi @j0shua - I'm going to hazard a guess that `inverseEnabled=true` is what's hampering your ingest rate. Quite frankly, this feature hasn't been heavily used and consequently, we haven't spent a lot effort optimizing for it. Without enabling inverse frames, you should see throughputs in the millions of bits per second (depending on hardware/cluster size/network/etc.)

If you really need the inverse index functionality for your use case, I would ask that you break this comment out into a separate issue, so that we can discuss possible solutions there and get it prioritized.

**Comment by j0shua** [comment] 2017-12-07 16:05
Thanks @jaffee!

That was it. After creating a new index without `inverseEnabled` I was able to load the entire data set this morning.

**Comment by jaffee** [comment] 2017-12-07 16:38
@j0shua that's good to hear - and again, if you do need that functionality, I'm sure we can improve it - we just haven't seen it be very useful and so haven't devoted much effort to it.

**Comment by jaffee** [comment] 2018-02-21 22:29
The original issue here (not having "scheme" in the response to `/fragment/nodes`) seems to be fixed (at least I am unable to reproduce it). However the problem of specifying `0.0.0.0` as the bind address is still very much alive. Is anyone opposed to me closing this ticket and breaking that out into a separate ticket?

**Comment by travisturner** [comment] 2018-04-17 21:10
The `0.0.0.0` bind address  issue is being tracked in #1129

**Closed by travisturner** 2018-04-17 21:10 UTC
